---
server:
    servlet:
        context-path: /feedFacade
        use-forward-headers: true
    use-forward-headers: true
    forward-headers-strategy: FRAMEWORK
grails:
    profile: web
    codegen:
        defaultPackage: feedfacade
    spring:
        transactionManagement:
            proxies: false
    resources:
        pattern: '/**'
    plugin:
        console:
            baseUrl: 'console'
info:
    app:
        name: '@info.app.name@'
        version: '@info.app.version@'
        grailsVersion: '@info.app.grailsVersion@'
spring:
    main:
        banner-mode: "off"
    groovy:
        template:
            check-template-location: false
    jmx:
        unique-names: true
management:
    security:
        enabled: true
    endpoints:
        enabled-by-default: true
    endpoint:
        jmx:
            enabled: true
        health:
            enabled: true
            db:
                enabled: true
            livenessstate:
                enabled: true
            readinessstate:
                enabled: true
            defaults:
                enabled: true
            probes:
                enabled: true
            group:
                exploratory:
                    include: readinessState,livenessState
            show-details: when-authorized
            show-components: when-authorized
            roles: ROLE_ADMIN,ROLE_USER
        info:
            enabled: true
        configprops:
            enabled: true
        loggers:
            enabled: true
        web:
            exposure:
                include: 'health,info'
    health:
        probes:
            enabled: true
---
grails:
    mime:
        disable:
            accept:
                header:
                    userAgents:
                        - Gecko
                        - WebKit
                        - Presto
                        - Trident
        types:
            all: '*/*'
            atom: application/atom+xml
            css: text/css
            csv: text/csv
            form: application/x-www-form-urlencoded
            html:
              - text/html
              - application/xhtml+xml
            js: text/javascript
            json:
              - application/json
              - text/json
            multipartForm: multipart/form-data
            pdf: application/pdf
            rss: application/rss+xml
            text: text/plain
            hal:
              - application/hal+json
              - application/hal+xml
            xml:
              - text/xml
              - application/xml
    urlmapping:
        cache:
            maxsize: 1000
    controllers:
        defaultScope: singleton
    converters:
        encoding: UTF-8
    views:
        default:
            codec: html
        gsp:
            encoding: UTF-8
            htmlcodec: xml
            codecs:
                expression: html
                scriptlets: html
                taglib: none
                staticparts: none
        encoding: UTF-8
    cors:
        enabled: true
endpoints:
    jmx:
        unique-names: true

---
hibernate:
    cache:
        queries: false
        use_second_level_cache: false
        use_query_cache: false

dataSource:
    pooled: true
    jmxExport: true
---
environments:
    development:
        server:
          port: 8081
        dataSource:
            dbCreate: update
            url: jdbc:postgresql://postgres:5432/feedfacadedev
            username: feedfacade
            password: feedFacade
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            properties:
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        sysusers:
            - name: admin
              pass: ChangeMeImmediately
              display: Admin
              email: admin@semweb.co
              roles:
                - ROLE_ADMIN
                - ROLE_USER
    test:
        dataSource:
            dbCreate: create-drop
            # dbCreate: update
            url: jdbc:postgresql://postgres:5432/feedfacadetest
            username: feedfacade
            password: feedFacade
            driverClassName: org.postgresql.Driver
            dialect: org.hibernate.dialect.PostgreSQLDialect
            properties:
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: false
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
        sysusers:
            - name: admin
              pass: admin
              display: Admin
              email: admin@semweb.co
              roles:
                - ROLE_ADMIN
                - ROLE_USER
    production:
        dataSource:
            dbCreate: update
            url: "${FF_DB_URL:jdbc:postgresql://postgres:5432/feedfacade}"
            username: "${FF_USERNAME:feedfacade}"
            password: "${FF_PASSWORD:feedFacade}"
            driverClassName: "${FF_JDBC_DRIVER:org.postgresql.Driver}"
            dialect: "${FF_HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}"
            properties:
                initialSize: 5
                maxActive: 50
                minIdle: 5
                maxIdle: 25
                maxWait: 10000
                maxAge: 600000
                timeBetweenEvictionRunsMillis: 5000
                minEvictableIdleTimeMillis: 60000
                validationQuery: SELECT 1
                validationQueryTimeout: 3
                validationInterval: 15000
                testOnBorrow: true
                testWhileIdle: true
                testOnReturn: true
                jdbcInterceptors: ConnectionState
                defaultTransactionIsolation: 2 # TRANSACTION_READ_COMMITTED
---
fah:
    sourceList: https://s3-eu-west-1.amazonaws.com/alert-hub-sources/json
environments:
    development:
        fah:
            localFeedSettings: "${user.home}/.grails/localFeedSettings.json"
    test:
        fah:
            localFeedSettings: "${user.home}/.grails/localFeedSettings.json"
    production:
        fah:
            localFeedSettings: /localFeedSettings.json
